'use client';
import Header from "@components/Header"
import Image from "next/image"
import { fira } from "@utils/font"

export default function Photos() {
    return (
        <Header>
            <div className="flex justify-center items-center">
                <div className="md:grid grid-cols-2 gap-28 mt-16 mr-20 sm:grid">
                    <div>
                        <Image
                            src="/assets/first-hike17.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike16.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike15.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike14.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike12.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike11.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike10.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike8.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike7.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike4.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike2.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/first-hike.png"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/dead-forest.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/fire.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/outline.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/shadow.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/boroichi.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/hackwithyou.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/ok-computer.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/work-in-progress.jpg"
                            className=""
                            alt="logo"
                            width={700}
                            height={700}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/shadow-tree.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/highway-concerto.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/mentei.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/quantum-syuto-highway.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/selfie.png"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/second-hike5.png"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/second-hike4.png"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/second-hike2.png"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/second-hike.png"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/quatum-eye.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                    <div>
                        <Image
                            src="/assets/syuto-highway.jpg"
                            className=""
                            alt="logo"
                            width={800}
                            height={800}
                        />
                    </div>
                </div>
            </div >
        </Header>
    )
}